
<?php
require 'config/db.php';
//insert.php

if(isset($_REQUEST['inviteMsg'] ) OR isset($_REQUEST['playerIds']) OR isset($_REQUEST['userIdnos']) OR 
isset($_REQUEST['playerNames']) OR isset($_REQUEST['scoutNames']) OR isset($_REQUEST['inviteStates']) OR isset($_REQUEST['resultPoss'])) {
$userIdnos = $_REQUEST['userIdnos'];
$playerIds = $_REQUEST['playerIds'];
$playerNames = $_REQUEST['playerNames'];
$scoutNames = $_REQUEST['scoutNames'];
$inviteMsg = $_REQUEST['inviteMsg'];
$inviteStates = $_REQUEST['inviteStates'];
$resultPoss = $_REQUEST['resultPoss'];


echo $inviteMsg;
echo "<br>";
echo $playerIds;

// set status comment to 0
$inviteNotif = 0; // GENERATED BY PHP no JS

$sqlInsertInvite = "INSERT INTO player_invites (player_id, scout_id, player_pos, player_name, scout_name, invite_msg, invite_status, invite_notif) 
VALUES('$playerIds', '$userIdnos', '$resultPoss', '$playerNames', '$scoutNames', '$inviteMsg', '$inviteStates', '$inviteNotif')";


if ($conn->query($sqlInsertInvite) === TRUE) {
  echo "New record created successfully";
} else {
  echo "Error: " . $sqlInsertInvite . "<br>" . $conn->error;
}

} // end of POST AJAX

?>
